### ISSUE TITLE
MacでのWindowの位置

### ISSUE THREAD

**Issue by DaddyF** [CSReviser/CaptureStream#14]
語学講座の位置の記憶がうまく反映されません。

CaptureStream.appを動作させると、語学講座CSの画面が表示されます。その位置を好きな場所に移動させると、Windows版では、次回にCaptureStream.appを立ち上げたときに、その場所を覚えているのですが、Mac版では、もとに戻ってしまいます。これは、レコーディングの画面も同じです。デバッグ環境がないとのことですので、デバッグは難しいと思いますが、普通に使うには問題ありません。一応、お知らせまで。

**Comment by CSReviser** [comment]
この問題はMac版で発生していた設定ファイル(iniファイル)の保存が出来ない問題と同じ原因ではないかと推測します。
もし、そうであれば2023/01/13版で解決すると思います。

**Comment by DaddyF** [comment]
試してみましたが、駄目でした。
この問題を確認してから、遡れるだけ遡ってテストしてみましたが、そもそも、Originalから移行したときから駄目だったようですので、もう少し根本的な問題かと思います。また、iniファイルやstylesheet-mac.qss、ffmpegの位置は、MacOSフォルダーの中ではなく、もっとユーザがすぐに見られる位置にあったと記憶しています(うろ覚えなので、確かありませんが)。最初に移行したときから、うまく行かなかったのではないかと想像しています。ですので、今回の修正(フォルダーの場所を指定する)には少し驚いています。元々、iniのフォルダーは決まっていて、修正が反映されたと思いますので、そのあたりの移行がうまく行かなかったのかと思います。あまり、大きな不都合を感じていないので、このままでもOKです。

**Comment by DaddyF** [comment]
追記しますと、stylesheet-mac.qssでフォントは修正していますが、今までも、うまく行っていました。フォルダーの位置のも指定していますが、うまく行っています。今回の修正には、それで少し驚いているということです。

**Comment by CSReviser** [comment]
2023/01/13版では改善されなかった事、了解しました。ご連絡ありがとうございます。

ffmpegのパス変更は2022/04/14版で行っています。ffmpegのパスを認識できない不具合の対策で実施しましたが、iniファイルの不具合を作り込む事になったようです。

Window位置の記憶、読み込み方法は他のOSと共通です。現状Macでは同じ方法ではダメの可能性はあります。また、originalの実行ファイルと公開された最終ソースファイルが違う、一致していない可能性もあります。

蛇足ですが、originalのLinux版はWindow位置が記憶出来ないとしてWindow位置を覚える機能は省いていますが、現在はWindows版と同じ方法でWindow位置の記憶、読み込みが機能しています。

いずれにしても、この問題はペンディングとして、現時点ではMac版はこの機能は対象外とさせていただきます。

**Comment by CSReviser** [comment]
[CaptureStream-Macintosh-20230120-1.dmg](https://github.com/CSReviser/CaptureStream/releases/download/20230120/CaptureStream-Macintosh-20230120-1.dmg)
Window位置を記憶する別の方法をMac版のみ仕込んでありますが、動作しないでしょうか？可能であればご確認ください。

**Comment by CSReviser** [comment]
ソースファイルMac向けに「これがないとウィンドウタイトルがメニューバーに隠れる」というコメントが入った処理があり、メニューバーの高さ分、下げている（？）と思われます。
この処理を削除する、または、初回のみ実施するように変更すれば良い？のかもしれません。
いずれにしても、実機がないので確認できませんが。

**Comment by DaddyF** [comment]
テスト版を作成していただけますと、Testします。

**Comment by CSReviser** [comment]
ご確認いただきありがとうございます。本件クローズとしたします。
