### ISSUE TITLE
[Mac] Stylesheet

### ISSUE THREAD

**Issue by DaddyF** [CSReviser/CaptureStream#22]
保存フォルダが引き継がれ、うまく動作していることを確認しました。
Requestですが、stylesheet-mac.qssを外出しにして、引き継げないでしょうか。
現在、版数が変わるたびに、コピーし直していますが、前のものをそのまま使えるほうが便利かと思われます。
保存フォルダの位置が引き継がれますので、同じ用に、stylesheet-mac.qssも引き継がれると良いと思われます。

**Comment by CSReviser** [comment]
ご意見、ご要望ありがとうございます。
Macについて知識がないので具体的にどうすれば良いのかわかりません。
仰るご要望の趣旨は理解しているつもりです。
しかし、今回の仕様変更も手探り状況で改善したつもりが、bugを作り込む結果となってしまいました。
申し訳ありませんが、現時点では制限事項とさせていただきます。

**Comment by CSReviser** [comment]
[CaptureStream-Macintosh-20230120-1.dmg](https://github.com/CSReviser/CaptureStream/releases/download/20230120/CaptureStream-Macintosh-20230120-1.dmg)

指定された保存フォルダ内にstylesheetが存在する場合、保存フォルダ内のstylesheetを優先するように変更しました。
動作確認はできていません。動作確認していただけますか？またstylesheetの保存先が別に適切な場所があるなら教えてください。

**Comment by DaddyF** [comment]
はい、stylesheetが保存先を優先することを確認できました。
保存先は、CaptureStream.iniと同じ場所がいいと思われます。
たとえば、カスタマイズからライブラリのPreference/CaptureStreamのフォルダに行けて、そこに、stylesheet-mac.qssとCaptureSteam.iniがあるとか。
添付されているffmpegも、CaptureStreamのフォルダにある方を優先するという仕様にすると、変更したい人は、そこに置いたものが優先され、私のように触らなくてもいい人は、defaultを使うというのもありと思われます。
次の添付のスクリーンショットは、画面が起動のたびに、どのくらい下がるかを示したものです。裏側のFinderの上部から、語学講座の上部までの差が1回の起動で下がる大きさです。参考になればと思います。
たぶん、クローズするときに、その位置を覚えていないか、起動するときに、覚えていた位置を取り込んでいないかのどちらかと思われます。どこかに、defaultのいちがあるのだろうと思います。また、毎回下がるのは、画面のtopにメニューがあるので、それを避けるために、本来は、1回だけ、下げるような仕様であるのに、前回の位置に、また、下げる大きさを足してから、下げているのだろうと思います。位置情報の縦が0の場合には足して、それ以外は足さないようにしたら、うまくいきそうですが、どこのソースコードなのかわからないので、確認できていません。
よろしくお願い致します。

￼

**Comment by CSReviser** [comment]
動作確認ありがとうございます。
「Mac OS で、ユーザーライブラリフォルダーはデフォルトで非表示になっている」ということのようでしたので、通常ユーザーはアクセスしないと考え、意図してユーザが指定した保存フォルダにしましたが、iniファイルと同じ場所が良いと言うことであれば、そのようにいたします。
但し、Mac向け独自機能は最小限にしたい、実機も知識もないところで、通常ユーザがアクセスしない場所にユーザを誘導するような機能をメニューに入れるという機能は採用したくない、という理由で採用を見送らせていただきます。

また、図を貼り付けて頂いたようですが、表示されておりません。windowの上下方向の位置の話かと思いますが、微調整が必要ということであれば、実機がないとやはり調整は困難かと思います。次回改版時にこの機能は削除します。

**Comment by CSReviser** [comment]
[CaptureStream-Macintosh-20230121-test.dmg](https://github.com/CSReviser/CaptureStream/releases/download/20230121/CaptureStream-Macintosh-20230121-test.dmg)

テスト用作成しました。
pathの優先度：順番に見に行って最初に存在したファイルを使用する。
ffmpeg、stylesheet各々別に検索するので、各々別フォルダにあっても動作します。それぞれ先に見つけたほうを使います。
（１）保存フォルダ（ユーザが指定）
（２）"〜/Library/Preferences/<APPNAME>"　
　　　但し、<APPNAME>フォオルダは作成していない
（３）"〜/Library/Preferences"
（４）デフォルト

**Comment by DaddyF** [comment]
ありがとうございました。
(1)、(3)、(4)は動作するようです。
色々試してみましたが、要望が多すぎたようで、少し複雑になりすぎた感じがします。すみません。
ユーザが指定できるのは、保存フォルダだけですので、(1)と(4)だけで十分のような気がしてきました。Preferencesにはファイルが多すぎて、わからなくなりそうです。
語学講座のフォルダと、ini, ffmpeg, stylesheetのフォルダを分けておければ良さそうですが、これらの3つのファイルを変更する人は、Macにもある程度慣れているので、これらのファイルはデフォルトに置くのが見つけやすいかと思います。ただし、版数が変わるときには、Saveしておいて、新しい版に移動する手間がかかりますが、あまり触ることがないでしょうから、問題なさそうです。

**Comment by CSReviser** [comment]
動作確認ありがとうございます。
記載忘れましたがメニューバー分下げる処理を削除してあります。Window位置はどうでしょうか？

**Comment by DaddyF** [comment]
直っていました。ありがとうございます。On Jan 22, 2023, at 5:25, CSReviser ***@***.***> wrote:﻿
動作確認ありがとうございます。
記載忘れましたがメニューバー分下げる処理を削除してあります。Window位置はどうでしょうか？

**Comment by DaddyF** [comment]
Windowsの位置の問題は解消されていました。こちらもありがとうございました。

**Comment by CSReviser** [comment]
ご確認ありがとうございました。本件クローズとしたします。
