### ISSUE TITLE
Macでの表示のずれ

### ISSUE THREAD

**Issue by DaddyF** [CSReviser/CaptureStream#26]
以前にも問題があって、修正していただいた語学番組の選択表示部分が、また、元に戻っていました。開くたびに、下にずれていきます。また、レコーディングボタンを押すと、以前は選択表示のすぐ下に表示されていましたが、右にずれて重なっています。大きな問題ではありませんが、まずは、お知らせまで。
Mac版です。

**Comment by CSReviser** [comment]
バグ連絡ありがとうございます。
対応が遅れ申し訳ありません。語学講座CS2に開発を移行した事もあって見落としていました。
不具合をご確認いただいたのは2023/02/25版でしょうか？
ソースコードを確認したところNew_GUI（02/25版）に修正箇所が反映できていなかった事を確認しました。
ご連絡ありがとうございました。

**Comment by DaddyF** [comment]
はい、その版でテストしました。現在の最新版です。

よろしくお願い致します。
深津

**Comment by CSReviser** [comment]
New_GUI版に移行を考えていましたが、New_GUI版は採用しない事にしました。
従来のGUIで2024年度版2024/04/19版をリリースしました。こちらをお試し下さい。長らく更新せず申し訳ありませんでした。
NHK語学のネット配信がらじるに移行したことに伴い、語学講座CSも語学講座CS2に移行しています。語学講座CS2への移行もご検討ください。

**Comment by DaddyF** [comment]
修正版をありがとうございました。
MacBook Pro 14-inch, 2021
Chip Apple M1 Pro
Memory 16 GB
macoS Sonoma 14.4.1
で簡単な動作確認済です。
